name: New Feature
description: Please fill out the required fields
title: ""
labels: ['enhancement']
type: 'Feature'
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a detailed description of the issue"
    validations:
      required: true
